//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteamCMDLauncher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SteamCMDLauncher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CSGO {
            get {
                object obj = ResourceManager.GetObject("CSGO", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] dedicated_server_list {
            get {
                object obj = ResourceManager.GetObject("dedicated_server_list", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Garrys_Mod {
            get {
                object obj = ResourceManager.GetObject("Garrys_Mod", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] L4D2 {
            get {
                object obj = ResourceManager.GetObject("L4D2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Holds hash keys to validate if the json loaded is official
        ///# Validation was runned after build at (YYYY-MM-DD): 2021-11-12 00:23:10
        ///# This process is automated using vlang ~ https://github.com/vlang/v
        ///CSGO=3a8d668b2fe0e109aa77b0ffc4a88990aab36cfaafa3e9ae6d4fb08b8175cc53
        ///Garrys Mod=2d5f8799bdea7e8d3428facdf8b729ee7f2de737e23777a9d7c17153438a9fa2
        ///L4D2=ef613b5806c4c448637b7a33456d96c65fb4f307f980fd157641a09b6e562bad
        ///TF2=a2fdb85983093f034d2046704b41385096f5156f307d84c4c446d6c8b0a791f0.
        /// </summary>
        public static string res_hash {
            get {
                return ResourceManager.GetString("res_hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	// Look at: https://steamdb.info/depot/X/
        ///	// Replace &apos;X&apos; with depot id (usually offset by 1 on wards -&gt; 4021 (4020 + 1)
        ///
        ///	// [NOTE] Currently all Windows depots - None for Linux or Mac OS yet
        ///
        ///	// Garrys Mod
        ///	&quot;4020&quot;: [ &quot;/garrysmod&quot; ],
        ///
        ///	// CSGO
        ///	&quot;740&quot;: [ &quot;/csgo&quot; ],
        ///
        ///	// CS 1.6 / Half Life
        ///	&quot;90&quot;: [ &quot;/cstrike&quot; ],
        ///
        ///	// 7 Days to Die
        ///	&quot;294420&quot;: [ &quot;.7DaysToDieServer.exe&quot;, &quot;/7DaysToDieServer_Data&quot; ],
        ///
        ///	// ASTRONEER
        ///	&quot;728470&quot;: [ &quot;/Astro&quot; ],
        ///
        ///	// Age of Chivalry
        ///	&quot;17515&quot;: [ &quot;/ageofchivalry [rest of string was truncated]&quot;;.
        /// </summary>
        public static string server_file_search {
            get {
                return ResourceManager.GetString("server_file_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] TF2 {
            get {
                object obj = ResourceManager.GetObject("TF2", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
